version: 2
build:
  os: ubuntu-20.04  # Specify the operating system (e.g., ubuntu-20.04)
  tools:
    python: "3.8"  # Specify the version of Python
sphinx:
  configuration: docs/source/conf.py  # Path to your Sphinx conf.py file
